---

- hosts : test-servers
  vars :
  - warName : UserDetails.war
  - warLocalPath : /var/lib/jenkins/workspace/UserDetailsAnsible/UserDetails/wars
  - warRemotePath : /usr/share/tomcat/webapps

  tasks :
   - name : copy war to node
     copy : src={{ warLocalPath }}/{{ warName }} dest={{ warRemotePath }}/{{ warName }}


     notify :
        - Restart tomcat7

  handlers :
   - name : Restart tomcat7
     command : systemctl start tomcat